name = "zeroth_maroon_quokka-24b6"
version = "1.0.0"

[deployment]
permission = "public"
nodes = 1

[build]
dir = "build"
entry = "zeroth_maroon_quokka-24b6-debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "zeroth_maroon_quokka-24b6-release.wasm"
command = "npm run build:release"
